### PR TITLE
Added some space between ICW & KPK logo

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by irvan-putra** [comment]
Please solve the conflict.

**Comment by ghost** [comment]
How do I solve the conflict?
I don't see the tutorial 😅

**Comment by irvan-putra** [comment]
https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/

^ there :D

**Comment by ghost** [comment]
Actually I dont edit it locally😅, I edit it using github **online**
So what should I did? I only put `<br>` tag between ICW adn KPK logo 😬
I didnt do anything beside^
@vandeput

**Comment by irvan-putra** [comment]
Ok, I fixed it. Anyway, you really need to learn command line :)

**Pull request merged**
